ACHIEVEMENTS = {
    "FIRST_DRINK": {"name": "🍺 First Drink", "description": "Played your first game."},
    "FIRST_WIN": {"name": "🏆 First Win", "description": "Won your first hand."},
    "FIRST_LOSS": {"name": "💸 First Loss", "description": "Lost your first hand."},
    "PUSH_IT": {"name": "🤝 Push It", "description": "Finished a hand with a push."},
    "BLACKJACK": {"name": "🃏 Blackjack!", "description": "Hit a natural blackjack."},
    "DOUBLE_TROUBLE": {"name": "💰 Double Trouble", "description": "Used Double Down."},
    "HOT_STREAK": {"name": "🔥 Hot Streak", "description": "Win 3 games."},
    "ON_A_HEATER": {"name": "📈 On A Heater", "description": "Win 10 games."},
    "DOWN_BAD": {"name": "📉 Down Bad", "description": "Lose 10 games."},
    "BROKE_AGAIN": {"name": "💀 Broke Again", "description": "Reach 0 gold."},
    "GOLD_HOARDER": {"name": "🏦 Gold Hoarder", "description": "Reach 5,000 gold."},
    "TAVERN_ROYALTY": {"name": "👑 Tavern Royalty", "description": "Reach 10,000 gold."},
    "REGULAR": {"name": "🎰 Regular", "description": "Play 25 games."},
    "VETERAN": {"name": "🍻 Tavern Veteran", "description": "Play 100 games."},
    "DRAGONS_LUCK": {"name": "🐉 Dragon's Luck", "description": "Win with 21."},
    "BUST_MAGNET": {"name": "🧨 Bust Magnet", "description": "Bust 10 times."},
    "BIG_WINNER": {"name": "🪙 Big Winner", "description": "Win 500+ gold in one hand."},
    "HIGH_ROLLER": {"name": "💎 High Roller", "description": "Wager 5,000 gold."},
    "HOUSE_FAVORITE": {"name": "😈 The House's Favorite", "description": "Lose 5,000 gold."},
    "FOUNDER": {"name": "🏆 Founder of The Tavern", "description": "The one responsible for everyone's gambling addiction."},
    "MATH_FIRST_BRAINCELL": {"name": "🧠 First Braincell", "description": "Complete your first Math Drill."},
    "MATH_ACTUALLY_STUDYING": {"name": "📚 Actually Studying", "description": "Get 10 correct Math Drill answers."},
    "MATH_MENTAL_MENACE": {"name": "🔥 Mental Math Menace", "description": "Get 5/5 on a Medium Math Drill."},
    "MATH_BIG_BRAIN": {"name": "👑 Big Brain at the Bar", "description": "Get 5/5 on a Hard Math Drill."},
    "MATH_QUICK_MATHS": {"name": "⚡ Quick Maths", "description": "Answer a Math Drill question correctly in under 3 seconds."},
    "HANGMAN_FIRST_GRAVE": {"name": "🪦 First Grave", "description": "Play your first Hangman game."},
    "HANGMAN_LETTER_GREMLIN": {"name": "🔤 Letter Gremlin", "description": "Guess 25 letters in Hangman."},
    "HANGMAN_NOT_TODAY": {"name": "🧠 Not Today, Undertaker", "description": "Win a Hangman game as a guesser."},
    "HANGMAN_UNDERTAKERS_DUE": {"name": "🕯️ Undertaker's Due", "description": "Win a Hangman game as Undertaker."},
    "HANGMAN_DOWN_TO_WIRE": {"name": "💀 Down to the Wire", "description": "Win Hangman with 5 of 6 mistakes."},
}
